spring:
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER,END #nie mo?e byc spacji po ";"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true # Whether to enable logging of SQL statements.
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always